name: flujo 4
on: [push]

jobs:
  pruebas:
    runs-on: ubuntu-latest
    steps:
      - name: "adicion de nombres al archivo"
        run: echo "Juan >> alumnos.txt"
             echo "Pedro >> alumnos.txt"
            echo "Maria >> alumnos.txt"
      - name: Crear Archivo
        run: touch alumnos.txt