name: flujo 4
on: [push]

jobs:
  pruebas:
    runs-on: ubuntu-latest
    steps:
      - name: Mensaje
        run: echo "primeras interacciones con Git action"
      - name: Crear Archivo
        run: touch alumnos.txt